### ISSUE TITLE
Add code of conduct document (first-timers-only). Issue #1

### ISSUE THREAD

**Issue by leeyspaul** [DAVFoundation/ride-hailing-api#3]
# first-timers-only
This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for helping make drones fly, cars find charging stations, and people and goods get from place to place.

Find more first-timers-only issues here.

Thank you for your help ❤️

# What is this project?
DAV (Decentralized Autonomous Vehicles) is a non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, boats, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Ride Hailing App API
One of the first projects being built by the DAV Foundation is a decentralized ride hailing app. This app connects drivers and passengers directly to each other. The GitHub repository you are looking at is the API that drives this ride hailing app for both passengers and drivers.

# How you can help
To help create an open and welcoming environment, we would like to have a [code of conduct](https://opensource.guide/code-of-conduct/) document as part of this project.

Please add a file called code_of_conduct.md to the root of the project. This file should be based on the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html). This document requires an email address in it. Please enter tal@dav.network

## Contributing to ride hailing api 
 - [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
 - [ ] Comment on this issue that you would like to do it (if you're the first you can start working on it immediately)
 - [ ] Open the [ride hailing api](https://github.com/DAVFoundation/ride-hailing-api) GitHub page and click the ★ Star and then ⑂ Fork buttons.
 - [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/ride-hailing-api.git`
 - [ ] Add the file
 - [ ] Commit your changes and push your local changes back to github with `$ git push -u origin master`
 - [ ] Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/ride-hailing-api) and create a pull request for your changes.
 - [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #1)
 - [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.
## Asking for help
We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our gitter channel. We are always happy to help 😄

We sometimes feature the work done by the community on our website. If you would like your GitHub user excluded from that, please email tal@dav.network

**Comment by LowLevel96** [comment]
@leeyspaul  Hi, I would like to work on this. This will be my first open-source contribution

**Comment by mariolo1985** [comment]
Thanks for the help @LowLevel96! We hope to see more contributions from you to the open source community. 😃
